# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3cd8beb866cfadee59a6e442a6d2b947"
name = "metafield-ui-extension-99"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]
