api_version = "2025-07"

[[extensions]]
name = "shipping-delay-message"
handle = "shipping-delay-message"
type = "ui_extension"
uid = "5c3b23b9-b182-f240-4b06-07cc44b19fa19b33b20d"

[[extensions.targeting]]
module = "./src/Checkout.tsx"
target = "purchase.checkout.cart-line-item.render-after"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#api-access
api_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#metafields
[[extensions.metafields]]
namespace = "custom"
key = "shipping_delay_message"
